# Generated by Django 2.0.7 on 2018-07-14 04:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zayacab', '0002_driver_passenger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passenger',
            new_name='Commuter',
        ),
    ]
