# Generated by Django 2.0.7 on 2018-07-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayacab', '0004_dummy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE'), ('BOOKED', 'BOOKED')], default='OFFLINE', max_length=10),
            preserve_default=False,
        ),
    ]
