# Generated by Django 2.0.7 on 2018-07-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayacab', '0007_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'ONLINE'), ('OFFLINE', 'OFFLINE'), ('BOOKED', 'BOOKED')], default='OFFLINE', max_length=10),
        ),
    ]
